const Types={
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    GET_USERS_LIST:'GET_USERS_LIST',
    ADD_AND_UPDATE_USER:'ADD_AND_UPDATE_USER',
    ADD_AND_UPDATE_FLOOR_LIST:'ADD_AND_UPDATE_FLOOR_LIST',
    EDIT_USER:'EDIT_USER',
    DELETE_USER:'DELETE_USER',
    CREATE_USER:'CREATE_USER',
    NULLIFY_SERVICE:'NULLIFY_SERVICE',
    GET_FLOORS_LIST:'GET_FLOORS_LIST',
    DELETE_FLOOR:'DELETE_FLOOR',
    STOP_LOADING:'STOP_LOADING',
    START_LOADING:'START_LOADING'
};
export  default Types;